apiVersion: v1 
kind: ServiceAccount
metadata:
  name: catalog-serviceaccount
  annotations: 
    azure.workload.identity/client-id: 7c439d62-654c-492c-bf44-72dc8b44c7f5
  labels:
    azure.workload.identity/use: "true"