apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        azure.workload.catalog/use: "true"
    spec:
      serviceAccountName: catalog-serviceaccount
      containers:
        - name: catalog
          image: playeconomyacr.azurecr.io/play.catalog:1.0.4
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: playeconomy-key-vault
            - name: ServiceSettings__Authority
              value: https://playeconomy-dns-service.eastus.cloudapp.azure.com/identity-svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5009
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5009
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5009
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - port: 80
      targetPort: 5009

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-serviceaccount
  annotations:
    azure.workload.identity/client-id: 7c439d62-654c-492c-bf44-72dc8b44c7f5
  labels:
    azure.workload.identity/use: "true"
